### ISSUE TITLE
Update Error strict mode in glue mode

### ISSUE THREAD

**Issue by hydrotik** [hydrotik/node-hapi-react-redux-sass-typescript-mongo-webpack-hmr-gulp#261]
/Watts/node_modules/glue/lib/index.js:4
const Path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dadams/Desktop/Watts/src/global/server/index.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! watts@0.1.0 start: `node ./src/global/server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the watts@0.1.0 start script 'node ./src/global/server/server.js'.
npm ERR! This is most likely a problem with the watts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/global/server/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls watts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Watts/npm-debug.log

**Comment by hydrotik** [comment]
remember to nvm use 5 and remove npm_modules if errors persist
